rust-cli/anstyle

crates/git/src/lib.rs
crates/owo/src/lib.rs
crates/termcolor/src/lib.rs
crates/yansi/src/lib.rs

- anstyle-git: Add extension trait to provide method on `anstyle::Style`
- anstyle-owo: Add extension trait to provide `to_owo` method on `anstyle::Style`
- anstyle-termcolor: Add extension trait to provide `to_termcolor` method on `anstyle::Style`
- anstyle-yansi: Add extension trait to provide `to_yansi` method on `anstyle::Style`

Add extension traits

---

crates/git/Cargo.toml

colorparse is deprecated in favor of anstyle-git.

docs(git): Add "colorparse" keyword to help people find anstyle-git

---

crates/yansi/src/lib.rs

Right now, the "Bright" distinction is just ignored and they're folded into the same colors. But "bright" (e.g. "bright blue"), as far as I can tell historically, is a synonym for "bold" (e.g. "bold blue").
https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit

fix(yansi): Handle Bright foreground colors as bold

---

crates/anstyle/examples/dump.rs
crates/anstyle/src/color.rs
crates/anstyle/src/effect.rs
crates/anstyle/src/style.rs

Rather than breaking this out into its own enum, I decided to just treat
them as independent effects.
Fixes #28

feat(anstyle): Support additional underline styles 

---

crates/anstyle-parse/benches/parse.rs
crates/anstyle-parse/src/lib.rs

This makes it so users can just specify `print`, not much of a win.
The big win will be when we add batch printing support as this will
allow fewer interruptions.

feat(parse): Let Perform control print vs execute 

---

crates/anstyle-parse/benches/parse.rs
crates/anstyle-parse/examples/parselog.rs
crates/anstyle-parse/src/lib.rs
crates/anstyle-parse/tests/testsuite.proptest-regressions
crates/anstyle-parse/tests/testsuite.rs

`advance_str` is much easier to implement than `advance_bytes` as it
doesn't have to deal with a UTF-8 state machine mixed in with the slice
gathering.
Performance
tl;dr faster than all but the most dense of escape code cases
```
rg_help.vte/advance_byte
time:   [19.407 µs 19.470 µs 19.540 µs]
rg_help.vte/advance_str
time:   [6.9290 µs 6.9606 µs 6.9933 µs]
rg_help.vte/advance_byte(strip)
time:   [25.557 µs 25.681 µs 25.817 µs]
rg_help.vte/advance_str(strip)
time:   [6.4233 µs 6.4521 µs 6.4817 µs]
rg_linus.vte/advance_byte
time:   [434.35 µs 436.07 µs 437.83 µs]
rg_linus.vte/advance_str
time:   [379.78 µs 381.75 µs 383.95 µs]
rg_linus.vte/advance_byte(strip)
time:   [471.51 µs 474.86 µs 480.77 µs]
rg_linus.vte/advance_str(strip)
time:   [374.54 µs 375.69 µs 376.88 µs] …
```

feat(parse): Parser::advance_str for bulk operations

---

crates/anstyle/src/style.rs

While `anstyle` isn't targeting being a styling crate, only style definitions, this is a nice convenience when you don't need a lot of styling features.

feat(anstyle): Add Style::render_reset

---

crates/anstyle/examples/dump.rs
crates/anstyle/src/effect.rs

This is after testing in wezterm.
Notes:
- westerm encourages `:` over `;` but we want `;` for max compatibility
- Underline colors are not working
- `4:n` underline styles are not working

fix(anstyle): Adjust underline behavior

---

crates/anstyle-wincon/examples/dump.rs
crates/anstyle-wincon/src/console.rs
crates/anstyle-wincon/src/lib.rs
crates/anstyle-wincon/src/lockable.rs
crates/anstyle-wincon/src/stream.rs

This moves the `Console` so the original, with its stale state, doesn't
get used.
To make this easier to test, I also added support for non-Windows

feat(wincon): Allow locking the Console

---

crates/anstyle-ansi-term/src/lib.rs
crates/anstyle-crossterm/src/lib.rs
crates/anstyle-git/src/lib.rs
crates/anstyle-lossy/src/lib.rs
crates/anstyle-lossy/src/palette.rs
crates/anstyle-ls/src/lib.rs
crates/anstyle-owo-colors/src/lib.rs
crates/anstyle-roff/src/lib.rs
crates/anstyle-stream/src/adapter/wincon.rs
crates/anstyle-stream/src/wincon.rs
crates/anstyle-termcolor/src/lib.rs
crates/anstyle-wincon/examples/dump.rs
crates/anstyle-wincon/examples/set.rs
crates/anstyle-yansi/src/lib.rs
crates/anstyle/examples/dump.rs
crates/anstyle/src/color.rs
crates/anstyle/src/style.rs

fix(anstyle)!: Clean up the API

---

Cargo.lock
crates/anstyle-stream/Cargo.toml
crates/anstyle-stream/src/auto.rs

This supports
- [`NO_COLOR`](https://no-color.org/)
- [`CLICOLOR` / `CLICOLOR_FORCE`](https://bixense.com/clicolors/)
- `TERM` per [`termcolor`](https://github.com/BurntSushi/termcolor/blob/04966b49ff3516a724a6276c9b40b1716ff4f164/src/lib.rs#L255,L313)
I had originally wanted to leave this to the application but it is a pain to deal with
- `anstyle_stream::stdout` and `astyle_stream::print` become worthless
- We could let apps do it through the global but correctly avoiding wincon breaks this
`supports-color` takes [a different approach](https://github.com/zkat/supports-color/blob/f4fd9f4f62ea827d9be9620a5335db3dea5955b0/src/lib.rs#L91,L115):
- `COLORTERM`: since we aren't dealing with truecolor vs 256 vs 16, this mostly isn't needed
- We are more permissive in assuming 16 color support …

feat(stream): Support env-based auto-detection

---

Cargo.lock
crates/anstyle-stream/Cargo.toml
crates/anstyle-stream/src/auto.rs

This is a follow up to #72
CI is a common enough of a piped target that supports ANSI escape codes for us to treat it like `TERM` detection, I hope.  We'll see how feedback works out on this.

feat(stream): Auto-enabled color for CI

---

crates/anstream/src/strip.rs
crates/anstyle-roff/tests/test_roff.rs
crates/anstyle/src/color.rs
crates/anstyle/src/effect.rs
crates/anstyle/src/lib.rs
crates/anstyle/src/macros.rs
crates/anstyle/src/reset.rs
crates/anstyle/src/style.rs

These ended up having minimal benefit (`StripStream::write` and `Style::write_to` having the most) but I also feel these help make the code more straightforward.

perf: Try to optimize for binary size

---

crates/anstyle-crossterm/README.md

I guess it was copy-pasted and forgot to change.

Fix crossterm link text

---

crates/anstyle-git/src/lib.rs
crates/anstyle-ls/src/lib.rs
crates/anstyle/src/color.rs
crates/anstyle/src/style.rs

We might re-add this later but trying to be conservative for 1.0.  We're trying to avoid being clever.

fix(anstyle)!: Don't assume a color is FG

---

crates/anstyle/src/color.rs

Without this patch:
```
$ cargo test --no-default-features
Compiling anstyle v1.0.1 (/home/capitol/project/anstyle/crates/anstyle)
error[E0599]: no method named `to_string` found for opaque type `impl Display` in the current scope
--> crates/anstyle/src/color.rs:607:36
|
607 |         let actual = c.render_fg().to_string();
|                                    ^^^^^^^^^ method not found in `impl Display`
--> /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/string.rs:2503:8
|
= note: the method is available for `impl Display` here
|
= help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
|
602 +     use alloc::string::ToString;
|
For more information about this error, try …
```

gate the max_display_buffer on the std feature

---

crates/anstyle-owo-colors/src/lib.rs

Hi. The mapping of ansi colors to `owo-colors` is not correct for the bright colors. They are all mapped to normal and the bright blue to black. As this is a very simple bug I thought I could skip opening an issue, sorry if this is a problem.

fix ansi_to_owo_colors_color bright colors

---

crates/anstream/src/auto.rs
crates/anstream/src/lockable.rs
crates/anstream/src/wincon.rs
crates/anstyle-wincon/src/console.rs

Being generic has offered little benefit (maybe less boilerplate) but
has caused a lot of pain whenever I'm trying to make changes.

fix(anstream)!: Simplify locking code

---

crates/anstyle-termcolor/src/lib.rs

The but was found during the review of <https://github.com/rust-lang/cargo/pull/12655>.

fix(anstyle-termcolor): set effect correctly for transformations

---

crates/anstyle-wincon/src/console.rs
crates/anstyle-wincon/src/stream.rs

This decouples parse state from the `Console`.

refactor(wincon): Prepare for global stream state

---

crates/anstyle-wincon/src/console.rs
crates/anstyle-wincon/src/stream.rs

A lot of the complexity in designing `anstyle-wincon` comes back to the state tracking inside of it.  This state tracking is to help reduce redundant calls.  The primary user of this package is only calling it when the state changes.  However, this does still have a side effect of back-to-back styles having an extra color write + flush.  In at least my cases, this isn't too often and ... it is just legacy windows.

fix(wincon): Always reset at end of write

---

crates/anstream/src/auto.rs

These were missed when we dropped `is_terminal` dep

fix(stream): Remove some auto feature gating

---

crates/anstream/Cargo.toml
crates/anstream/src/macros.rs
crates/anstream/tests/macros.rs

fix(stream): Capture print macros in tests 

---

crates/anstream/src/auto.rs

Have a situation in cargo where we use `AutoStream::new` and then need to later check the color choice.  Rather than requiring the caller to check both values and `and` them together, let's just report it.
Ideally, we could remove those color choice checks but that will take a bit of plumbing work.

feat(stream): Query the current choice

---

crates/anstream/benches/stream.rs
crates/anstream/src/buffer.rs
crates/anstream/src/lib.rs
crates/anstream/src/macros.rs
crates/anstream/src/stream.rs
crates/anstream/src/strip.rs
crates/anstream/src/wincon.rs
crates/anstyle-wincon/src/stream.rs

We also deprecate `Buffer`.
This is because we no longer have to deal with foreign traits.

feat(stream): Allow wrapping a Vec directly

---

crates/anstream/src/adapter/strip.rs

This fixes a soundness issue where we create invalid UTF-8 data and then
do a `str::from_unchecked` on release builds.
This ensures we ignore up-to the start of UTF-8 sequences and not
mid-way through.
We need to find more ways to prop test this to help catch issues like this.
This supersedes #157
Fixes #156

fix(stream): Don't break out of UTF8 character part-way

---

crates/anstream/Cargo.toml
crates/anstream/src/auto.rs
crates/anstream/src/lib.rs

The `colorchoice` dep is light enough of a dependency that it shouldn't be a problem and this simplifies calling code when `auto` is conditional.

feat(anstream): Expose AutoStream::new always

---

crates/anstyle/examples/dump-style.rs

dump-style lacked a trailing newline at the end of its output, leaving
the cursor on the same line as its last line, and causing the user's
prompt to end up on that same line. Add a trailing newline.

fix(anstyle): Add trailing newline to dump-style example output

---

crates/anstyle/src/reset.rs
crates/anstyle/src/style.rs

This is an unusual suggestion, but I've tried it out in practice and it feels
really comfortable to use. I wanted to run it by you to see if it seemed
reasonable.
I found the requirement to call `.render()` and `.render_reset()` rather
verbose, particularly when trying to render several color styles in one line. I
started thinking about ways to make that more convenient, and this idea
occurred to me.
With this PR applied, `Style` and `Reset` implement `Display` directly,
rendering the ANSI code, without having to call `.render()`. That part I'm
hoping will be relatively uncontroversial; that's in the first two commits.
The more unusual part of this PR: if you set the alternate format flag, a
`Style` will print its reset code, instead.
The combination of the two makes it easy to use inline …

RFC: Style code/reset rendering via Display

---

crates/anstyle/src/color.rs
crates/anstyle/src/effect.rs
crates/anstyle/src/reset.rs

Before, we were inconsistent about this.  Now, we err on the side of
always ignoring the settings as there isn't really much reason to pad
ansi escape codes and the padding could accumulate over multiple calls.

fix(anstyle): Don't display with formatter's settings 

---

crates/anstyle-query/src/lib.rs

CLICOLOR_FORCE was changed in jhasse/clicolors#12 then jhasse/clicolors#20
While this is a behavior change, I'm going to consider it minor and not bump major.

fix(query)!: Update CLICOLOR_FORCE to check non-empty 

---

crates/anstyle-git/src/lib.rs

git 2.46 adds support for 12-bit hex colors, written `#RGB` with three
hex digits, in addition to the existing 24-bit `#RRGGBB` support with
six. Add support and test cases for this.

Support 12-bit hex colors `#RGB`, for compatibility with git 2.46

---

crates/anstyle-query/src/lib.rs

docs(query): Clean up confusing aspects

---

crates/anstream/src/buffer.rs
crates/anstream/src/stream.rs
crates/anstyle-wincon/src/ansi.rs
crates/anstyle-wincon/src/stream.rs

Implement `RawStream for &mut impl RawStream, Box<impl RawStream>` (and the other required traits) instead of implementing for each `&mut T`/`Box<T>` manually.
This includes existing implementations, plus the ones that were missing in certain cases and all future ones, so only new implementations are added.
Split from https://github.com/rust-cli/anstyle/pull/221.

refactor: Implement `RawStream` for `&mut T` and `Box<T>` generically

---

crates/anstream/src/stream.rs
crates/anstyle-wincon/src/stream.rs

~~Based on #223. Only the last commit is from this PR.~~
Closes #220.
Implements `RawStream` (and the other required traits) for `dyn Write + Send {,+ Sync}`.

feat: implement AutoStream for dyn Write + auto traits

---

crates/anstream/src/stream.rs

Missed in https://github.com/rust-cli/anstyle/pull/224. Implement the same changes for `AsLockedWrite`.
I've added tests to make sure that these types both implement `RawStream` and that `AutoStream` implements `std::io::Write`.

feat: Implement AsLockedWrite generically too

---

crates/anstyle/src/color.rs
crates/anstyle/src/effect.rs
crates/anstyle/src/reset.rs

A known issue with `write!` is that it's slower and generates more code that direct calls to `write_str`, unfortunately even on the simple case of `"{str}"`. See https://github.com/rust-lang/rust/issues/76490.
I've verified with Godbolt that it is still the case: https://godbolt.org/z/sq3M8xWfo

perf: avoid using write! macro with single `str`

---

crates/anstream/src/_macros.rs
crates/anstyle-svg/src/lib.rs

chore: fix some comments

---

Cargo.lock
crates/anstyle-wincon/Cargo.toml
crates/anstyle-wincon/src/windows.rs

refactor: Avoid once_cell on new Rust

---

crates/anstyle-svg/src/lib.rs

I'm using this crate within `triagebot` for syntax highlighting of the logs. We have extra content we need to add in the HTML, meaning I can't simply use `render_html` or I'd need to parse the HTML, which would be suboptimal. So instead, I keep the two parts that I need: the style and the HTML "body".

Extend `anstyle-svg` API to make it easier to integrate it into bigger HTML pages

---

crates/anstyle-crossterm/src/lib.rs

`BrightBlue` was mapped to `Black` instead of `Blue`.

fix(crossterm): fix color conversion

---

crates/anstream/src/auto.rs
crates/anstream/src/strip.rs
crates/anstream/src/wincon.rs

The main concern we have is `&mut Inner` because our processing of input is stateful and this can mess things up.
Adding an `as_inner` doesn't have that problem and can be useful for any custom behavior users have added that they want to query. This particularly came up with converting Rustup from termcolor to anstream because of their test stream.

feat(anstream): Provide read-only access to inner stream
